= LettuceMod
:linkattrs:
:project-owner:   redis-developer
:project-name:    lettucemod
:project-group:   com.redis
:project-version: 1.5.1

image:https://github.com/redis-developer/lettucemod/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg[Download, link="https://search.maven.org/#search|ga|1|{project-name}"]
image:https://img.shields.io/github/license/{project-owner}/{project-name}.svg["License", link="https://github.com/{project-owner}/{project-name}"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg?token=A5IX98M8JT["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]
image:https://img.shields.io/badge/Forum-Modules-blue["forum", link=https://forum.redis.com/c/modules/]

LettuceMod is a Java client for https://docs.redis.com/latest/modules/[Redis Modules] based on https://lettuce.io[Lettuce]. It supports the following modules in standalone or cluster configurations:

* https://oss.redis.com/redisgears/[RedisGears]
* https://oss.redis.com/redisjson/[RedisJSON]
* https://oss.redis.com/redisearch/[RediSearch]
* https://oss.redis.com/redistimeseries/[RedisTimeSeries]

== Getting Started

=== Java
.Maven
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>{project-name}</artifactId>
    <version>{project-version}</version>
</dependency>
----

.Gradle
[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    implementation '{project-group}:{project-name}:{project-version}'
}
----

=== Spring
.Maven
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>spring-lettucemod</artifactId>
    <version>{project-version}</version>
</dependency>
----

.Gradle
[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    implementation '{project-group}:spring-lettucemod:{project-version}'
}
----

== Usage

=== Java

==== Standalone Client
[source,java]
----
RedisModulesClient client = RedisModulesClient.create("redis://localhost:6379"); // <1>

StatefulRedisModulesConnection<String, String> connection = client.connect(); // <2>

RedisModulesCommands<String, String> commands = connection.sync(); // <3>
----
<1> Create a modules client
<2> Connect to Redis server

==== Cluster Client
[source,java]
----
RedisURI node1 = RedisURI.create("node1", 6379);
RedisURI node2 = RedisURI.create("node2", 6379);

RedisModulesClusterClient clusterClient = RedisModulesClusterClient.create(Arrays.asList(node1, node2)); // <1>

StatefulRedisModulesClusterConnection<String, String> connection = clusterClient.connect(); // <2>

RedisModulesAdvancedClusterCommands<String, String> commands = connection.sync(); // <3>
----
<1> Create a cluster modules client
<2> Connect to Redis servers
<3> Use the sync, async, or reactive API

==== Connection Pool
[source,java]
----
GenericObjectPoolConfig<StatefulRedisModulesConnection<String, String>> config = new GenericObjectPoolConfig<>();
config.setMaxTotal(4); // <1>
// ...
GenericObjectPool<StatefulRedisModulesConnection<String, String>> pool = ConnectionPoolSupport.createGenericObjectPool(client::connect, config); // <2>
----
<1> Create a pool configuration
<2> Create the connection pool

=== Spring

==== Client
[source,java]
----
@Component
public class MyComponent {

    @Autowired
    StatefulRedisModulesConnection<String, String> connection;

    // ...
}
----

==== Connection Pool
[source,java]
----
@Component
public class MyComponent {

    @Autowired
    GenericObjectPool<StatefulRedisModulesConnection<String, String>> pool;

    // ...
}
----

=== RedisGears
[source,java]
----
RedisGearsCommands<String, String> gears = connection.sync(); // <1>

gears.pyExecute("GearsBuilder().run('person:*')"); // <2>
----
<1> Use sync, async, or reactive RedisGears commands
<2> Execute a RedisGears Python function

=== RedisJSON
[source,java]
----
RedisJSONCommands<String, String> json = connection.sync(); // <1>

json.set("arr", ".", "[1,2,3]"); // <2>
----
<1> Use sync, async, or reactive RedisJSON commands
<2> Set a JSON value

=== RediSearch
[source,java]
----
RediSearchCommands<String, String> search = connection.sync(); // <1>

search.create("beers", Field.text("name").build(), Field.numeric("ibu").build()); // <2>

SearchResults<String, String> results = search.search("beers", "chou*"); // <3>
----
<1> Use sync, async, or reactive RediSearch commands
<2> Create an index
<3> Search the index

=== RedisTimeSeries
[source,java]
----
RedisTimeSeriesCommands<String, String> ts = connection.sync(); // <1>

ts.add("temp:3:11", 1548149181, 30); // <2>
----
<1> Use sync, async, or reactive RedisTimeSeries commands
<2> Append a new sample to the series

=== Pipelining
[source,java]
----
RedisModulesAsyncCommands<String, String> commands = connection.async();

commands.setAutoFlushCommands(false); // <1>

List<RedisFuture<?>> futures = new ArrayList<>(); // <2>
for (MyEntity element : entities()) {
    futures.add(commands.sugadd("names", element.getName(), element.getScore()));
}

commands.flushCommands(); // <3>

boolean result = LettuceFutures.awaitAll(5, TimeUnit.SECONDS,
        futures.toArray(new RedisFuture[0])); // <4>

connection.close(); // <5>
----
<1> Disable auto-flushing
<2> Perform a series of independent calls
<3> Write all commands to the transport layer
<4> Synchronization example: Wait until all futures complete
<5> Later

=== Connection Pooling
[source,java]
----
try (StatefulRedisModulesConnection<String,String> connection = pool.borrowObject()) {
    RedisModulesAsyncCommands<String, String> commands = connection.async();
    // ...
} catch (Exception e) {
    log.error("Could not get a connection from the pool", e);
}
----