= LettuceMod
:linkattrs:
:project-owner:   redis-developer
:project-name:    lettucemod
:project-group:   com.redis
:project-version: 1.5.1

image:https://github.com/redis-developer/lettucemod/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg[Download, link="https://search.maven.org/#search|ga|1|{project-name}"]
image:https://img.shields.io/github/license/{project-owner}/{project-name}.svg["License", link="https://github.com/{project-owner}/{project-name}"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg?token=A5IX98M8JT["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]
image:https://img.shields.io/badge/Forum-Modules-blue["forum", link=https://forum.redis.com/c/modules/]

Java client for https://docs.redis.com/latest/modules/[Redis Modules] based on https://lettuce.io[Lettuce]

== Modules

LettuceMod supports the following modules:

* https://oss.redis.com/redisearch/[RediSearch]
* https://oss.redis.com/redisgears/[RedisGears]
* https://oss.redis.com/redistimeseries/[RedisTimeSeries]

== Getting Started

=== Maven

Add LettuceMod dependency to your POM file:

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>{project-name}</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== Gradle
Add LettuceMod dependency to your `build.gradle` file:

[source,groovy]
[subs="verbatim,attributes"]
.build.gradle
----
dependencies {
    implementation '{project-group}:{project-name}:{project-version}'
}
----

== Usage

=== Client
[source,java]
----
RedisModulesClient client = RedisModulesClient.create("redis://localhost:6379"); <1>
StatefulRedisModulesConnection<String, String> connection = client.connect(); <2>
----
<1> Create a modules client
<2> Connect to Redis server

=== RedisGears
[source,java]
----
RedisGearsCommands<String, String> gears = connection.sync(); <1>
gears.pyExecute("GearsBuilder().run('person:*')"); <2>
----
<1> Use sync, async, or reactive RedisGears commands
<2> Execute a RedisGears Python function

=== RedisJSON
[source,java]
----
RedisJSONCommands<String, String> json = connection.sync(); <1>
json.set("arr", ".", "[1,2,3]"); <2>
----
<1> Use sync, async, or reactive RedisJSON commands
<2> Set a JSON value

=== RediSearch
[source,java]
----
RediSearchCommands<String, String> search = connection.sync(); <1>
search.create("beers", Field.text("name").build(), Field.numeric("ibu").build()); <2>
SearchResults<String, String> results = search.search("beers", "chou*"); <3>
----
<1> Use sync, async, or reactive RediSearch commands
<2> Create an index
<3> Search the index

=== RedisTimeSeries
[source,java]
----
RedisTimeSeriesCommands<String, String> ts = connection.sync(); <1>
ts.add("temp:3:11", 1548149181, 30); <2>
----
<1> Use sync, async, or reactive RedisTimeSeries commands
<2> Append a new sample to the series
