name: 'Early Access'

on:
  push:
    branches: [ main ]

jobs:
  earlyaccess:
    name: 'Early Access'
    if: github.repository == 'redis/lettucemod' && startsWith(github.event.head_commit.message, 'Releasing version') != true
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/early-access.yml@main
    with:
      jreleaser-arguments: full-release
      java-version: 19
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
